import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy — Flock",
  description: "What Flock and its browser extension do with your data.",
};

/**
 * Required by the Chrome Web Store, and linked from the extension listing.
 *
 * Written to be accurate rather than reassuring: reviewers compare this against
 * what the code actually does, and every claim here is one the source backs up.
 */
export default function PrivacyPage() {
  return (
    <div className="prose">
      <h1>Privacy</h1>
      <p className="prose-lead">
        Flock is a tool for listing your own clothing on marketplaces you already sell on.
        This page covers both the website and the browser extension.
      </p>

      <h2>What the extension does</h2>
      <p>
        The extension fills in marketplace sell forms using listings you prepared in your own
        Flock account. It fills fields and stops — <strong>it never submits a listing for
        you</strong>, and it never asks for or receives your marketplace password. It works
        inside the browser session you are already signed in to.
      </p>

      <h2>What the extension stores</h2>
      <p>Two things, locally in your browser, using <code>chrome.storage.local</code>:</p>
      <ul>
        <li>
          A pairing token that authenticates the extension to your Flock account. It is
          generated by Flock, shown to you once, and stored only as a hash on our side.
        </li>
        <li>
          Two preferences: whether to fill in a background window, and whether to advance the
          form automatically.
        </li>
      </ul>
      <p>
        It does not read or store your browsing history, your marketplace account details, or
        the content of any page other than the sell form you asked it to fill.
      </p>

      <h2>What the extension sends</h2>
      <p>
        It requests your own listing data from Flock, and after you publish a listing it
        sends back the resulting marketplace URL so your inventory reflects what is live.
        Nothing else leaves your browser, and nothing is sent to any third party.
      </p>

      <h2>What the website stores</h2>
      <ul>
        <li>
          <strong>Your account.</strong> Name and email address from Google Sign-In. We never
          receive your Google password.
        </li>
        <li>
          <strong>Your inventory.</strong> The garments you add, their photos, and the listings
          you generate. Photos are held in private storage and served only to you through
          short-lived signed links.
        </li>
        <li>
          <strong>Model output.</strong> When you use photo identification, the photos are sent
          to Anthropic&apos;s API to be read, and the structured result is stored against the
          item so you can see what was inferred and correct it.
        </li>
      </ul>

      <h2>What we don&apos;t do</h2>
      <ul>
        <li>We do not sell or share your data with third parties.</li>
        <li>We do not use it for advertising, profiling, or credit decisions.</li>
        <li>We do not have access to your marketplace accounts.</li>
      </ul>

      <h2>Deleting your data</h2>
      <p>
        Delete your account yourself, from Settings — it removes every garment, listing, sale, photo and message, cancels any subscription first, and cannot be undone by us afterwards. Email us if you would rather we did it. Removing the extension
        deletes its local storage, including the pairing token; you can also revoke a pairing
        code at any time from the Extension page in Flock.
      </p>

      <h2>Contact</h2>
      <p>
        <a href="mailto:mlyin03@gmail.com" className="link">
          mlyin03@gmail.com
        </a>
      </p>

      <p className="prose-fine">Last updated 17 August 2026.</p>
    </div>
  );
}
